misc: pkgbuild-jetbrains-update: cleanup, accept multiple args

diff --git a/misc/pkgbuild-jetbrains-update b/misc/pkgbuild-jetbrains-update
--- a/misc/pkgbuild-jetbrains-update
+++ b/misc/pkgbuild-jetbrains-update
@@ -3,7 +3,27 @@
 set -eo pipefail
 shopt -s lastpipe
 
-. lib.sh || exit
+# shellcheck source=../lib/lib.sh
+. lib.sh
+
+
+#
+# constants
+#
+
+declare -A JETBRAINS_CODES=(
+	[clion]=CL
+	[goland]=GO
+	[datagrip]=DG
+	[pycharm]=PCP
+	[rustrover]=RR
+	[webstorm]=WS
+)
+
+
+#
+# args
+#
 
 _usage() {
 	cat <<EOF
@@ -19,42 +39,71 @@ declare -A _ARGS=(
 parse_args _ARGS "$@" || usage
 
 case "${#ARGS[@]}" in
-0) DIR=. ;;
-1) DIR="${ARGS[0]}" ;;
-*) usage "Expected 0 or 1 positional arguments, got ${#ARGS[@]}" ;;
+0) DIRS=(.) ;;
+*) DIRS=("${ARGS[@]}") ;;
 esac
 
-[[ -d "$DIR" && -f "$DIR/PKGBUILD" ]] || usage "Invalid directory: $DIR"
-cd "$DIR"
 
-declare -A filename_to_arch
-sed_expr=()
+#
+# functions
+#
 
-mksrcinfo
-cat .SRCINFO | sed -nr 's|\tsource_([^ ]+) = (.+::)?(.+)|\1 \3|p' | while read arch link; do
-	filename="${link##*/}"
-	filename_to_arch["$filename"]="$arch"
-done
+update_one() (
+	set -eo pipefail
+	shopt -s lastpipe
+	eval "$(ltraps)"
 
-cat .SRCINFO | sed -nr 's|\tsource_([^ ]+) = (.+::)?(.+)|\1 \3|p' | while read arch link; do
-	echo "${link}.sha256"
-done | parallel curl -fsSL | while read sha256sum filename; do
-	filename="${filename#\*}"
-	arch="${filename_to_arch[$filename]}"
-	sed_expr+=(
-		-e "s|(sha256sums_$arch)=.*|\1=('$sha256sum')|"
-	)
+	local dir="$1"
 
-done
+	if ! [[ -d "$dir" && -f "$dir/PKGBUILD" ]]; then
+		die "Invalid directory: $dir"
+	fi
 
-trace sed -r "${sed_expr[@]}" -i PKGBUILD
-mksrcinfo
-if (( ARG_STAGE || ARG_COMMIT )); then
+	cd "$dir"
+	mksrcinfo
+
+	local name ver
+	name="$(aur srcinfo -Qr '.pkgbase')"
+	ver="$(aur srcinfo -Qr '.pkgver')"
+	local LIBSH_LOG_PREFIX="$name"
+
+	declare -A filename_to_arch
+	declare -a sed_expr
+
+	cat .SRCINFO | sed -nr 's|\tsource_([^ ]+) = (.+::)?(.+)|\1 \3|p' | while read arch link; do
+		filename="${link##*/}"
+		filename_to_arch["$filename"]="$arch"
+	done
+
+	cat .SRCINFO | sed -nr 's|\tsource_([^ ]+) = (.+::)?(.+)|\1 \3|p' | while read arch link; do
+		echo "${link}.sha256"
+	done | parallel 'set -x; curl -fsSL' | while read sha256sum filename; do
+		filename="${filename#\*}"
+		arch="${filename_to_arch[$filename]}"
+		sed_expr+=(
+			-e "s|(sha256sums_$arch)=.*|\1=('$sha256sum')|"
+		)
+	done
+
+	sed -r "${sed_expr[@]}" -i PKGBUILD
+	mksrcinfo
+
+	if ! [[ $ARG_STAGE || $ARG_COMMIT ]]; then
+		return
+	fi
+
+	if git diff-files --quiet && git diff-index --quiet HEAD --; then
+		log "No changes"
+		return
+	fi
+
 	git add PKGBUILD .SRCINFO
-fi
-if (( ARG_COMMIT )); then
-	name="$(aur srcinfo -Qr .pkgbase)"
-	ver="$(aur srcinfo -Qr .pkgver)"
+
+	if ! [[ $ARG_COMMIT ]]; then
+		return
+	fi
+
+	local kind build msg
 	if [[ $ver =~ ^([0-9.]+)$ ]]; then
 		msg="$name: $ver"
 	elif [[ $ver =~ ^([0-9.]+)([a-z]+)\+([0-9.]+)$ ]]; then
@@ -69,5 +118,13 @@ if (( ARG_COMMIT )); then
 
 		msg="$name: $ver $kind $build"
 	fi
+
+	log "Committing changes"
 	git commit -m "$msg"
-fi
+)
+
+rc=0
+for d in "${DIRS[@]}"; do
+	update_one "$d" || rc=1
+done
+exit "$rc"
