umount-iso: handle errors while unmounting whole image directory.

diff --git a/umount-iso b/umount-iso
--- a/umount-iso
+++ b/umount-iso
@@ -37,8 +37,8 @@ for file in "${!DIRS[@]}"; do
 
 		LODEVICE=$(< "$DIR/.partitions_base_directory")
 	else
-		echo "> Unmounting whole image"
-		umount -d "$DIR"
+		echo "> Unmounting whole image (loop-device will be removed)"
+		umount -d "$DIR" || { echo "==== FAILED TO UNMOUNT WHOLE IMAGE. WILL NOT CONTINUE BEYOND UNMOUNT STAGE." >&2; FAILED_UMOUNT=1; }
 	fi
 	(( "$FAILED_UMOUNT" )) && exit 1
 
