util: disk-clone: refactor, cleanup

diff --git a/util/disk-clone b/util/disk-clone
--- a/util/disk-clone
+++ b/util/disk-clone
@@ -1,133 +1,155 @@
 #!/bin/bash
 
-set -e
+set -eo pipefail
 shopt -s extglob
+shopt -s lastpipe
+
+. lib.sh || exit
 
 SRC="$1"
 DEST="$2"
 
+if ! [[ -b "$SRC" || -f "$SRC" ]]; then
+	die "Bad source: $SRC"
+fi
+
+if ! [[ -b "$DEST" || -f "$DEST" || ! -e "$DEST" ]]; then
+	die "Bad destination: $DEST"
+fi
+
+SRC_REAL="$SRC"
+DEST_REAL="$DEST"
+
 function blk_size() {
-	echo $(( $(blockdev --getsz "$1") * 512 ))
+	blockdev --getsize64 "$1"
 }
 
 function file_size() {
-	if [[ -f "$1" ]]; then
-		stat -c "%s" "$1"
+	stat -c "%s" "$1"
+}
+
+function maybe_size() {
+	local dev="$1"
+	if [[ -b "$dev" ]]; then
+		blk_size "$dev"
+	elif [[ -e "$dev" ]]; then
+		file_size "$dev"
 	else
 		echo 0
 	fi
 }
 
-if [[ -b "$SRC" ]]; then
-	SRC_IS_BLK=1
-	SRC_SIZE=$(blk_size "$SRC")
-else
-	SRC_SIZE=$(file_size "$SRC")
-fi
+function maybe_detach() {
+	local dev="$1"
+	if [[ "$dev" == /dev/loop* ]]; then
+		local origin="$(losetup -n -O BACK-FILE "$dev")"
+		log "  -> $dev (loop for $origin)"
+		losetup -d "$dev"
+	else
+		log "  -> $dev is not a loop device, not detaching"
+	fi
+}
 
-if [[ -b "$DEST" ]]; then
-	DEST_IS_BLK=1
-	DEST_SIZE=$(blk_size "$DEST")
-else
-	DEST_SIZE=$(file_size "$DEST" || echo 0)
-fi
+
+function maybe_remove_err() {
+	local dev="$1"
+	if [[ -b "$dev" ]]; then
+		log "  -> $dev, skipping block device"
+	else
+		log "  -> $dev"
+		rm -vf "$dev"
+	fi
+}
 
 function cleanup() {
-	echo ":: detach loop devices..."
+	log "detach loop devices"
 
-	if (( SRC_IS_BLK )); then
-		echo "   -> not detaching block device $SRC_LOOP"
-	else
-		echo "   -> $SRC_LOOP for src"
-		losetup -d "$SRC_LOOP"
-	fi
+	maybe_detach "$SRC"
+	maybe_detach "$DEST"
 
-	if (( DEST_IS_BLK )); then
-		echo "   -> not detaching block device $DEST_LOOP"
-	else
-		echo "   -> $DEST_LOOP for dest"
-		losetup -d "$DEST_LOOP"
-	fi
-	
-}
-
-function cleanup_err() {
-	echo ":: remove incomplete destination file"
-	if (( DEST_IS_BLK )); then
-		echo "   -> not removing block device $DEST"
-	else
-		rm -f "$DEST"
+	if ! (( success )); then
+		log "remove incomplete destination file"
+		maybe_remove_err "$DEST_REAL"
 	fi
 }
 
+success=0
 trap cleanup EXIT
-trap cleanup_err ERR
 
-echo ":: truncate '$DEST' to size of '$SRC'"
-if (( DEST_IS_BLK )); then
-	if (( DEST_SIZE >= SRC_SIZE )); then
-		echo "   -> not truncating block device $DEST of size $DEST_SIZE >= $SRC_SIZE"
+
+function maybe_truncate() {
+	local dev="$1"
+	local target="$2"
+	local dev_size="$(maybe_size "$dev")"
+	local target_size="$(maybe_size "$target")"
+	if [[ -b "$dev" ]]; then
+		if (( dev_size >= target_size )); then
+			log "  -> not truncating block device $dev of size $dev_size >= $target_size"
+		else
+			log "  -> block device $dev is of size $dev < $target_size, cannot proceed"
+		fi
 	else
-		echo "   -> block device $DEST is of size $DEST_SIZE < $SRC_SIZE, cannot proceed"
+		rm -f "$dev"
+		truncate --size "$target_size" "$dev"
 	fi
-else
-	rm -f "$DEST"
-	truncate --size "$SRC_SIZE" "$DEST"
-fi
-echo
+}
 
-echo ":: copy partition table"
+
+log "truncate '$DEST' to size of '$SRC'"
+maybe_truncate "$DEST" "$SRC"
+
+log "copy partition table"
 blkid "$SRC"
 SRC_PTTYPE="$(blkid -s PTTYPE -o value "$SRC")"
 case "$SRC_PTTYPE" in
 dos)
-	echo "   -> MBR detected -- using sfdisk"
+	log "  -> MBR detected -- using sfdisk"
 	sfdisk -d "$SRC" | sfdisk "$DEST"
 	;;
 gpt)
-	echo "   -> GPT detected -- using sgdisk"
+	log "  -> GPT detected -- using sgdisk"
 	TEMPFILE="$(mktemp)"
 	sgdisk -b "$TEMPFILE" "$SRC"
 	sgdisk -l "$TEMPFILE" "$DEST"
 	rm -f "$TEMPFILE"
 	;;
 *)
-	echo "   -> unknown partition table type '$SRC_PTTYPE'!"
+	log "  -> unknown partition table type '$SRC_PTTYPE'!"
 	false
 	;;
 esac
 echo
 
-echo ":: setup loop devices..."
-if (( SRC_IS_BLK )); then
-	SRC_LOOP="$SRC"
-	echo "   -> skipping loopback for block device $SRC"
-else
-	SRC_LOOP=$(losetup -Pf --show "$SRC")
-	echo "   -> '$SRC_LOOP' for '$SRC'"
-fi
 
-if (( DEST_IS_BLK )); then
-	DEST_LOOP="$DEST"
-	echo "   -> skipping loopback for block device $DEST"
-else
-	DEST_LOOP=$(losetup -Pf --show "$DEST")
-	echo "   -> '$DEST_LOOP' for '$DEST'"
-fi
-echo
+function maybe_loop() {
+	dev="$1"
+	if [[ -b "$dev" ]]; then
+		log "  -> $dev is block device, skipping"
+		echo "$dev"
+	else
+		local loop=$(losetup -Pf --show "$dev")
+		log "  -> $dev ($loop)"
+		echo "$loop"
+	fi
+}
+
+log "setup loop devices..."
+SRC="$(maybe_loop "$SRC")"
+DEST="$(maybe_loop "$DEST")"
+
 
 function arg_exists() { [[ -e "$1" ]]; }
 
-echo ":: clone partitions..."
-for src_part in "$SRC_LOOP"?*; do
+log "clone partitions..."
+for src_part in "$SRC"?*; do
 	# determine source partition number, accounting for two different naming schemas (diskXY and diskXpY)
-	partnr="${src_part##$SRC_LOOP?(p)}"
+	partnr="${src_part##$SRC?(p)}"
 
 	# determine destination naming schema
-	if arg_exists "${DEST_LOOP}p"*; then
-		dest_part="${DEST_LOOP}p${partnr}"
+	if arg_exists "${DEST}p"*; then
+		dest_part="${DEST}p${partnr}"
 	else
-		dest_part="${DEST_LOOP}${partnr}"
+		dest_part="${DEST}${partnr}"
 	fi
 
 	part_type="$(blkid "$src_part" -o value -s TYPE)"
@@ -155,3 +177,5 @@ for src_part in "$SRC_LOOP"?*; do
 
 	echo
 done
+
+success=1
