util: efivar-crud: refactor, accept new verbs 'list' and 'exists'

diff --git a/util/efivar-crud b/util/efivar-crud
--- a/util/efivar-crud
+++ b/util/efivar-crud
@@ -1,31 +1,11 @@
 #!/bin/bash
 
-function warn() {
-	echo "W: $*" >&2
-}
-
-function error() {
-	echo "E: $*" >&2
-}
-
-function die() {
-	error "$*"
-	exit 1
-}
-
-function check() {
-	local expr="$1"
-	shift
-
-	if ! eval "$expr"; then
-		die "in ${FUNCNAME[1]}: assertion '$expr' failed: $*"
-	fi
-}
+. lib.sh || exit
 
 function handle_fail() {
 	local cmd="$BASH_COMMAND" function="${FUNCNAME[1]}" exitcode="$?"
 
-	die "in ${FUNCNAME[1]}: command '$cmd' failed with exit-code $exitcode"
+	die "in $function: command '$cmd' failed with exit-code $exitcode"
 }
 
 EFIVARFS="/sys/firmware/efi/efivars"
@@ -63,6 +43,15 @@ function explicit_attrs() {
 	done
 }
 
+function make_attrs() {
+	local attrs="$1" variable="$2"
+	if (( ATTRS_SET )); then
+		explicit_attrs "$attrs"
+	else
+		efivar_attrs "$variable"
+	fi
+}
+
 function efivar_data() {
 	local name="$1"
 	check_var "$name"
@@ -72,8 +61,8 @@ function efivar_data() {
 function efivar_write() {
 	local name="$1" file="$2"
 	if [[ -e "$EFIVARFS/$name" ]]; then
+		chattr -i "$EFIVARFS/$name"
 		rm "$EFIVARFS/$name"
-		touch "$EFIVARFS/$name"
 	fi
 	hexdump -C "$file"
 
@@ -102,7 +91,7 @@ EOF
 	done
 }
 
-function usage() {
+function _usage() {
 	cat <<EOF
 Usage: efivar-crud [-a|--attrs ATTRS] ACTION ...
 
@@ -115,6 +104,13 @@ $(_usage_attrs)
 
 ACTION is an action to perform, followed by its own arguments.
 Possible actions:
+
+	efivar-crud list
+		List names of all currently existing EFI variables
+		in a format suitable for passing back into efivar-crud
+
+	efivar-crud exists VARIABLE
+		Return a code indicating whether VARIABLE exists
 
 	efivar-crud read VARIABLE
 		Read and print data of EFI variable specified by VARIABLE
@@ -142,30 +138,30 @@ EOF
 		
 }
 
-set -o pipefail
 trap handle_fail ERR
 
-ARGS=$(getopt -l "attrs:" -o "a:" -- "$@")
+ARGS=$(getopt -l "help,attrs:" -o "ha:" -- "$@")
 if (( "$?" )); then
     usage
-    exit 1
 fi
 eval set -- "$ARGS"
 
 while true; do
     case "$1" in
-        # HANDLING HERE
-		-a|--attrs)
-			ATTRS_SET=1
-			ATTRS=0
+	-a|--attrs)
+		ATTRS_SET=1
+		ATTRS=0
 
-			shift
-			IFS=:
-			for attr in $1; do
-				ATTRS="$(( ATTRS | ATTRIBUTE_LIST[$attr] ))"
-			done
-			unset IFS
-			;;
+		shift
+		IFS=:
+		for attr in $1; do
+			ATTRS="$(( ATTRS | ATTRIBUTE_LIST[$attr] ))"
+		done
+		unset IFS
+		;;
+	-h|--help)
+		usage
+		;;
         --)
             shift
             break
@@ -178,19 +174,33 @@ while true; do
 done
 
 if (( $# < 1 )); then
-	error "At least one argument expected."
-	usage
-	exit 1
+	usage "At least one argument expected."
 fi
 
 ACTION="$1"
 
+check_efivarfs
+
 case "$ACTION" in
+l|list)
+	if (( $# != 1 )); then
+		usage "Only one argument expected."
+	fi
+	find "$EFIVARFS" -mindepth 1 -maxdepth 1 -type f -printf '%P\n'
+	;;
+
+e|exists)
+	if (( $# != 2 )); then
+		usage "Two arguments expected."
+	fi
+	VARIABLE="$2"
+
+	[[ -f "$EFIVARFS/$VARIABLE" ]] && exit 0 || exit 1
+	;;
+
 r|read)
 	if (( $# != 2 )); then
-		error "Two arguments expected."
-		usage
-		exit 1
+		usage "Two arguments expected."
 	fi
 	VARIABLE="$2"
 	efivar_data "$VARIABLE" | convert_from_efi | sed -e 's/\x0$//'
@@ -198,9 +208,7 @@ r|read)
 
 r-a|read-attrs)
 	if (( $# != 2 )); then
-		error "Two arguments expected."
-		usage
-		exit 1
+		usage "Two arguments expected."
 	fi
 	VARIABLE="$2"
 	ATTRS="$(efivar_attrs "$VARIABLE" | od -A n --endian=little -t u4 | tr -d ' \n\t')"
@@ -214,61 +222,49 @@ r-a|read-attrs)
 
 w|write)
 	if (( $# != 3 )); then
-		error "Three arguments expected."
-		usage
-		exit 1
+		usage "Three arguments expected."
 	fi
 	VARIABLE="$2"
 	VALUE="$3"
 	TEMPFILE="$(mktemp)"
 	trap "rm -f '$TEMPFILE'" EXIT
 
-	if (( ATTRS_SET )); then
-		explicit_attrs "$ATTRS"                        > "$TEMPFILE"
-	else
-		efivar_attrs "$VARIABLE"                       > "$TEMPFILE"
-	fi
-	echo -ne "$VALUE\\0" | convert_to_efi             >> "$TEMPFILE"
+	{
+		make_attrs "$ATTRS" "$VARIABLE"
+		echo -ne "$VALUE\\0" | convert_to_efi
+	} > "$TEMPFILE"
 	efivar_write "$VARIABLE" "$TEMPFILE"
 	;;
 
 w-f|write-file)
 	if (( $# != 3 )); then
-		error "Three arguments expected."
-		usage
-		exit 1
+		usage "Three arguments expected."
 	fi
 	VARIABLE="$2"
 	FILE="$3"
 	TEMPFILE="$(mktemp)"
 	trap "rm -f '$TEMPFILE'" EXIT
 
-	if (( ATTRS_SET )); then
-		explicit_attrs "$ATTRS"                        > "$TEMPFILE"
-	else
-		efivar_attrs "$VARIABLE"                       > "$TEMPFILE"
-	fi
-	{ cat "$FILE"; echo -ne "\\0"; } | convert_to_efi >> "$TEMPFILE"
+	{
+		make_attrs "$ATTRS" "$VARIABLE"
+		{ cat "$FILE"; echo -ne "\\0"; } | convert_to_efi
+	} > "$TEMPFILE"
 	efivar_write "$VARIABLE" "$TEMPFILE"
 	;;
 
 w-f-r|write-file-raw)
 	if (( $# != 3 )); then
-		error "Three arguments expected."
-		usage
-		exit 1
+		usage "Three arguments expected."
 	fi
 	VARIABLE="$2"
 	FILE="$3"
 	TEMPFILE="$(mktemp)"
 	trap "rm -f '$TEMPFILE'" EXIT
 
-	if (( ATTRS_SET )); then
-		explicit_attrs "$ATTRS"                        > "$TEMPFILE"
-	else
-		efivar_attrs "$VARIABLE"                       > "$TEMPFILE"
-	fi
-	cat "$FILE"                                       >> "$TEMPFILE"
+	{
+		make_attrs "$ATTRS" "$VARIABLE"
+		cat "$FILE"
+	} > "$TEMPFILE"
 	efivar_write "$VARIABLE" "$TEMPFILE"
 	;;
 esac
