git/misc: git-merge-repeatedly: guard against non-conflict merge failures
`git merge` may return non-zero for reasons other than a merge failure,
at which point the current logic would happily see that both index and
worktree are clean and behave as if the merge succeeded.

Instead, add a special case to handle both index and worktree being
clean _immediately_ after a failed `git merge` invocation, treating it
as an unrecoverable error.

diff --git a/git/misc/git-merge-repeatedly b/git/misc/git-merge-repeatedly
--- a/git/misc/git-merge-repeatedly
+++ b/git/misc/git-merge-repeatedly
@@ -7,7 +7,20 @@ say() {
 	echo "${0##*/}: $*" >&2
 }
 
-if ! git merge "$@"; then
+if git merge "$@"; then
+	# dance to capture exit code of $SHELL (cannot use ! in the condition)
+	:
+else
+	rc=$?
+
+	# If we have a clean worktree and a clean index immediately after
+	# a failed merge invocation, something must have gone wrong
+	if git diff-files --quiet && git diff-index --quiet HEAD --; then
+		say "merge failed for unknown reason, aborting"
+		exit $rc
+	fi
+
+	# If (while) we have an unclean worktree, shell out to the user
 	while ! git diff-files --quiet; do
 		say "launching interactive shell"
 		say "to continue, resolve and stage conflicts and exit 0"
@@ -22,8 +35,10 @@ if ! git merge "$@"; then
 		fi
 	done
 
-	# if the user not just staged the resolution but committed it, play along
-	# also play along if the index turned out empty
+	# If we have an unclean index, commit it
+	# Unlike the above, at this point we can also have a clean index too:
+	# - if the user not just staged the resolution but committed it, play along
+	# - also play along if the index turned out empty
 	if ! git diff-index --quiet HEAD --; then
 		git commit --no-edit
 	fi
